import Head from "next/head";
import { Inter } from "next/font/google";
import { sanityClient, urlFor } from "@/lib/sanity";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

const recipesQuery = `*[_type == "recipe"] {
  _id,
  name,
  slug,
  mainImage
}
`;

export default function Home({ recipes }) {
  console.log(recipes);
  return (
    <>
      <Head>
        <title>Kap's Kitchen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome to Kap's Kitchen</h1>

      <ul className="recipe-list">
        {recipes?.length > 0 &&
          recipes.map((recipe) => (
            <li key={recipe.id} className="recipe-card">
              <Link href={`/recipes/${recipe.slug.current}`} legacyBehavior>
                <a>
                  <img
                    src={urlFor(recipe.mainImage).url()}
                    alt={recipe?.name}
                  />
                  <span>{recipe.name}</span>
                </a>
              </Link>
            </li>
          ))}
      </ul>
    </>
  );
}

export async function getStaticProps() {
  const recipes = await sanityClient.fetch(recipesQuery);
  return { props: { recipes } };
}
